### ISSUE TITLE
Thanks for this script.

### ISSUE THREAD

**Issue by kwyjibo-au** [T13nn3s/Resize-UserProfileDisk#1]
Thanks for this script. It will be very useful.

**Comment by T13nn3s** [comment]
Hi and thanks for your comment! According to your issue, the script doesn't work? What problems do you have?

**Comment by kwyjibo-au** [comment]
All good.

Got it working and edited comment on GitHub.

**Comment by T13nn3s** [comment]
Got it working without issues. Issue closed.
