### ISSUE TITLE
RDS Server - ALL User Sessions Break

### ISSUE THREAD

**Issue by PCFixerGuy** [T13nn3s/Resize-UserProfileDisk#12]
When running on a production server and the VHDX's are on a disk on the same RDP server, the process will search for ALL mounted VHDX files and DISMOUNT ALL of them, EVEN the ones that were read only, aka IN USE.  Yowza.  DON'T RUN DURING BUSINESS HOURS (from experience).

**Comment by T13nn3s** [comment]
I'm running this script sometimes in business hours, yes in production without any problems. Did you have used the ZeroFreeSpace parameter?

**Comment by T13nn3s** [comment]
Microsoft does not recommend to store the UPDs on the same server where the sessions are hosted. From that point of perspective is this script created.
