### ISSUE TITLE
diskpart unable to process spaces in filepaths

### ISSUE THREAD

**Issue by daskey** [T13nn3s/Resize-UserProfileDisk#2]
Line 294 - `Add-Content diskpart_script.txt "select vdisk file="$vhdx"` is missing quotation around $vhdx to write to file and pass to diskpart. If your UPD filepath contains spaces, you'll receive the below error in the Diskpart logfile.

"The arguments specified for this command are not valid."

Fix - change line 294 to `Add-Content diskpart_script.txt "select vdisk file=`"$vhdx`""`. Diskpart will successfully run "select vdisk file="E:\User Profile Disks\*.vhdx" instead of erroring on select vdisk file=E:\User Profile Disks\*.vhdx

**Comment by T13nn3s** [comment]
Script updated with the recommended fix. @daskey, can you please test and confirm that this issue has been resolved?

**Comment by T13nn3s** [comment]
Quotes are not resolving this issue. The issue reopened and changed are rolled back.

**Comment by daskey** [comment]
Need to add powershell escape characters before quotes. Formatting messed with original bug report but this is what worked for me.
![image](https://user-images.githubusercontent.com/13271393/78650913-2700bd00-78f2-11ea-8246-a8e7558a6562.png)

**Comment by kwyjibo-au** [comment]
![Capture](https://user-images.githubusercontent.com/62787398/78726869-44756b80-7972-11ea-8d65-2fb6d9dd9e5e.PNG)

**Comment by T13nn3s** [comment]
I will check this line and add the quotes and do sims tests with it.

**Comment by jscooksey** [comment]
I got the space issue resolved with this, but not as neat as what you have above.  Did that work?
    $fileString = 'select vdisk file="' + $UPD +  '"'
    Add-Content -Path compact.txt $fileString

**Comment by hcelik** [comment]
Hello,



Yes, seems working on my side.



Best regards,
--
Huseyin CELIK
Mobile : +41 79 916 68 32
E-mail : huseyin.celik@icloud.com

Le 11 mai 2020 à 5:26, Justin Cooksey <notifications@github.com> a écrit :






I got the space issue resolved with this, but not as neat as what you have above. Did that work?
$fileString = 'select vdisk file="' + $UPD + '"'
Add-Content -Path compact.txt $fileString
